site_name: Global CS
site_author: 'Global-CS-application'
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:   
  name: material
  language: zh
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: lime
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.integrate
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  custom_dir: overrides

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

plugins:
  - search

nav:
  - "index.md"
  - 项目介绍:
      - 查找指南: "Program/search.md"
      - 欧陆项目:
          - Ⅰ:
              - ETH MSCS: "Program/T0/ETH MSCS.md"
              - ETH MSDS: "Program/T0/ETH MSDS.md"
              - ETH Cyber Security: "Program/T0/ETH Cyber Security.md"
              - EPFL MSCS: "Program/T0/EPFL MSCS.md"

          - Ⅱ:
              - EPFL MSDH: "Program/T0.5/EPFL MSDH.md"
          - Ⅲ:
              - KTH MSML: "Program/T1/KTH MSML.md"
              - KTH MSCS: "Program/T1/KTH MSCS.md"
              - TUD MSCS: "Program/T1/TUD MSCS.md"
              - UvA AI: "Program/T1/UvA AI.md"
              - Aalto CS: "Program/T1/Aalto CS.md"
              - Aalto HCI: "Program/T1/Aalto HCI.md"
              - Aalto MLDSAI: "Program/T1/Aalto MLDSAI.md"
          - Ⅳ:
              - EIT欧盟奖学金: "Program/T1.5/EIT欧盟奖学金.md"
              - Erasmus欧盟奖学金: "Program/T1.5/EM欧盟奖学金.md"
              - TUE CS: "Program/T1.5/TUE CS.md"
              - KU CS: "Program/T1.5/KU CS.md"
              - Aarhus CS: "Program/T1.5/Aarhus CS.md"
              - UH CS: "Program/T1.5/UH CS.md"
              - UH DS: "Program/T1.5/UH DS.md"
              - University of Heidelberg DCS: "Program/T1.5/University of Heidelberg DCS.md"
          - Ⅴ:
              - UvA&VU CS: "Program/T2/UvA&VU CS.md"
              - DTU CS: "Program/T2/DTU CS.md"
              - DTU AI: "Program/T2/DTU AI.md"
              - Uppsala CS: "Program/T2/Uppsala CS.md"
              - TU Graz CS: "Program/T2/TU Graz CS.md"
              - TU Wien CS: "Program/T2/TU Wien CS.md"
              - University of Helsinki CS: "Program/T2/University of Helsinki CS.md"
              - CTH CAS: "Program/T2/CTH CAS.md"
              - University of Vienna DS: "Program/T2/University of Vienna DS.md"
              - FAU AI: "Program/T2/FAU AI.md"

          - Ⅹ:
              - UZH CS: "Program/TX/UZH CS.md"
              - UZH AI: "Program/TX/UZH AI.md"
              - UZH DS: "Program/TX/UZH DS.md"
              - TUM CS: "Program/TX/TUM CS.md"
              - University of Bonn CS: "Program/TX/University of Bonn CS.md"
              - University of Stuttgart CS: "Program/TX/University of Stuttgart CS.md"
              

      - 英国项目:
          - Ⅰ:
              - Cambridge MLMI: "Program/T0/Cambridge MLMI.md"
              - Cambridge ACS: "Program/T0/Cambridge ACS.md"
              - Oxford ACS: "Program/T0/Oxford ACS.md"
              - UCL CSML MSc: "Program/T0/UCL CSML MSc.md"
          - Ⅱ:
              - UCL DSML MSc: "Program/T0.5/UCL DSML MSc.md"
          - Ⅲ:
              - UCL ML MSc: "Program/T1/UCL ML MSc.md"
              - Edinburgh AI: "Program/T1/Edinburgh AI.md"
              - IC AIML: "Program/T1/IC AIML.md"
              - IC AC: "Program/T1/IC AC.md"
          - Ⅳ:
              - Edinburgh REST: "Program/T1.5/Edinburgh REST.md"
              - UCL CS Msc: "Program/T1.5/UCL CS Msc.md"
              - UCL CGVI: "Program/T1.5/UCL CGVI.md"

      - 香港项目:
            - HKUST BDT: "Program/T1.5/HKUST BDT.md"
            - HKUST IT: "Program/T1.5/HKUST IT.md"
            - HKU CS Msc: "Program/T1.5/HKU CS Msc.md"
            - CUHK CS Msc: "Program/T1.5/CUHK CS Msc.md"
            - CUHK IE: "Program/T1.5/CUHK IE.md"

      - 新加坡项目:
          - Ⅰ:
              - NUS Mcomp: "Program/T1.5/NUS Mcomp.md"
              - NTU MSAI: "Program/T1.5/NTU MSAI.md"
              - NTU MSDS: "Program/T1.5/NTU MSDS.md"
              - NTU Cyber Security: "Program/T1.5/NTU Cyber Security.md"
          - Ⅱ:
              - NUS CE: "Program/T2/NUS CE.md"

      - 日韩/其他项目:
          - KAIST CS: "Program/TX/KAIST CS.md"
          - UTokyo CS: "Program/TX/UTokyo CS.md"
          - KAUST CS Msc: "Program/TX/KAUST CS Msc.md"
  - 申请总结:
      - 23fall:
          - DIY指南 by @Lee-abcde: "summary/23fall/DIYguide.md"
  - 加入我们: "joinus.md"
#      - Ⅰ:
#          - ETH MSCS: "Program/T0/ETH MSCS.md"
#          - ETH MSDS: "Program/T0/ETH MSDS.md"
#          - EPFL MSCS: "Program/T0/EPFL MSCS.md"
#          - ETH Cyber Security: "Program/T0/ETH Cyber Security.md"
#          - Cambridge MLMI: "Program/T0/Cambridge MLMI.md"
#          - Cambridge ACS: "Program/T0/Cambridge ACS.md"
#          - Oxford ACS: "Program/T0/Oxford ACS.md"
#          - UCL CSML MSc: "Program/T0/UCL CSML MSc.md"
#          - UCL ML MSc: "Program/T0/UCL ML MSc.md"
#      - Ⅱ:
#          - EPFL MSDH: "Program/T0.5/EPFL MSDH.md"
#          - UCL DSML MSc: "Program/T0.5/UCL DSML MSc.md"
#      - Ⅲ:
#          - Edinburgh AI: "Program/T1/Edinburgh AI.md"
#          - IC AIML: "Program/T1/IC AIML.md"
#          - IC AC: "Program/T1/IC AC.md"
#          - KTH MSML: "Program/T1/KTH MSML.md"
#          - KTH MSCS: "Program/T1/KTH MSCS.md"
#          - TUD MSCS: "Program/T1/TUD MSCS.md"
#          - UvA AI: "Program/T1/UvA AI.md"
#      - Ⅳ:
#          - Europe Program:
#            - Edinburgh REST: "Program/T1.5/Edinburgh REST.md"
#            - UCL CS Msc: "Program/T1.5/UCL CS Msc.md"
#            - UCL CGVI: "Program/T1.5/UCL CGVI.md"
#            - EIT&EM欧盟奖学金: "Program/T1.5/EIT欧盟奖学金.md"
#            - TUE CS: "Program/T1.5/TUE CS.md"
#            - Aalto CS: "Program/T1.5/Aalto CS.md"
#            - Aalto  HCI: "Program/T1.5/Aalto HCI.md"
#            - Aalto MLDSAI: "Program/T1.5/Aalto MLDSAI.md"
#          - Asia Program:
#            - NUS Mcomp: "Program/T1.5/NUS Mcomp.md"
#            - NTU MSAI: "Program/T1.5/NTU MSAI.md"
#            - NTU MSDS: "Program/T1.5/NTU MSDS.md"
#            - NTU Cyber Security: "Program/T1.5/NTU Cyber Security.md"
#            - HKUST BDT: "Program/T1.5/HKUST BDT.md"
#            - HKUST IT: "Program/T1.5/HKUST IT.md"
#            - HKU CS Msc: "Program/T1.5/HKU CS Msc.md"
#            - CUHK CS Msc: "Program/T1.5/CUHK CS Msc.md"
#            - CUHK IE: "Program/T1.5/CUHK IE.md"
#      - Ⅴ:
#          - KU CS: "Program/T2/KU CS.md"
#          - UH CS: "Program/T2/UH CS.md"
#          - UvA&VU CS: "Program/T2/UvA&VU CS.md"
#          - NUS CE: "Program/T2/NUS CE.md"
#      - Ⅹ:
#          - UZH CS: "Program/TX/UZH CS.md"
#          - UZH AI: "Program/TX/UZH AI.md"
#          - UZH DS: "Program/TX/UZH DS.md"
#          - TUM CS: "Program/TX/TUM CS.md"
#          - KAIST CS: "Program/TX/KAIST CS.md"
#          - UTokyo CS: "Program/TX/UTokyo CS.md"
#          - KAUST CS Msc: "Program/TX/KAUST CS Msc.md"

repo_url: https://github.com/Global-CS-application/global-cs-application.github.io
repo_name: global-cs-application
edit_uri: edit/main/docs/

