site_name: Global CS
site_author: 'Global-CS-application'
theme:   

  name: material
  palette:
    primary: lime

nav:
  - "index.md"
  - 项目介绍:
      - T0:
        - ETH MSCS: "Program/T0/ETH MSCS.md"